# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff975229e5191dc953c73158f13138569f0b2b6b2354ffea5de982553c293b28431245bd9d38eb93175d722ea9145d4ab5bb3d1716488528d3a9a6927b90df23

test:
  secret_key_base: 66d31903c19bec1f43f2586bbf104c7c81b43c1df1e9de41ed776a1e93b430990e013e07f5d83e256bd55818879eb0f7b1397c98db6488ae88033c360c8c0c4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
